# Generated by Django 2.0.7 on 2021-07-15 13:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('feed', models.CharField(max_length=1000)),
                ('img', models.ImageField(upload_to='pics')),
                ('like', models.IntegerField()),
                ('comment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None)),
                ('share', models.CharField(max_length=100)),
            ],
        ),
    ]
