# Generated by Django 2.0.7 on 2021-07-28 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20210717_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=1000)),
                ('guess', models.CharField(max_length=10000)),
                ('message', models.CharField(max_length=10000)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('roomid', models.CharField(max_length=1000)),
            ],
        ),
    ]
