# Generated by Django 2.0.7 on 2021-07-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='guess',
        ),
    ]
